### ISSUE TITLE
Icon clipping in footer

### ISSUE THREAD

**Issue by benfrank241** [LangStream/langstream.github.io#10]
The VS Code icon in the footer doesn't fully show.

**Comment by eolivelli** [comment]
@ddieruf could you please take a look ?

**Comment by ddieruf** [comment]
Hi @benfrank241, thank you for contacting us. Are you referring to the VS Code link on langstream.ai (I've attached a shot)? Was there a page on the site where this was getting clipped?


![image](https://github.com/LangStream/langstream.github.io/assets/16946028/047d9437-2fe8-48e4-82f8-925e18651eac)

**Comment by benfrank241** [comment]
Yeah it’s right there in the image. On langstream.ai in the footer the VS code icon is only partially showing.


Sent from Yahoo Mail for iPhone


On Wednesday, October 11, 2023, 6:06 AM, David Dieruf ***@***.***> wrote:




Hi @benfrank241, thank you for contacting us. Are you referring to the VS Code link on langstream.ai (I've attached a shot)? Was there a page on the site where this was getting clipped?

**Comment by ddieruf** [comment]
Ahh yes I see it now. Ok thx.

**Comment by cdbartholomew** [comment]
This is fixed now. Thanks for reporting it, @benfrank241 

![image](https://github.com/LangStream/langstream.github.io/assets/22917476/412a502f-3419-42f9-988a-49e05b971e3f)
